import sys
import requests
from typing import Optional
import time
import urllib.parse

# GitHub login IDs, or (None, name) for someone without a GitHub account
# Use following command to get a rough idea who should be on this list:
# git shortlog -n -s -- ':!app/src/main/res/values*/strings.xml' ':!fastlane/metadata/android/' ':!readme*.md'
GITHUB_USERS = [
    "nift4",
    "123Duo3",
    "AkaneTan",
    "mikooomich",
    "imjyotiraditya",
    "WSTxda",
    "pxeemo",
    "saladnoober",
    "Lambada10",
    "lightsummer233",
    "nicholaswww",
    "Yuyuko1024",
    "ghhccghk",
    "banksio",
    "manum45",
    "lucaxvi",
    "tungnk123",
    (None, "kleidis"),
    "topazrn",
    "strongville",
    "SurFace81",
    "bggRGjQaUbCoE",
    "VishnuSanal",
    "HotarunIchijou",
    "someone5678",
    "PalanixYT",
    "N3Shemmy3",
    "SharnavM",
]

OUTPUT_KT = "app/src/main/java/org/akanework/gramophone/logic/utils/data/Contributors.kt"
API_BASE = "https://api.github.com/users/"
WEBLATE_BASE = "https://hosted.weblate.org"
WEBLATE_REPORTS = WEBLATE_BASE + "/api/reports/"

HEADERS = {
    "Accept": "application/vnd.github+json",
}
WEBLATE_HEADERS = {
    "Accept": "application/json",
}

try:
    with open("fastlane/creds.txt", "r", encoding="utf-8") as f:
        HEADERS["Authorization"] = "Bearer " + f.read().strip()
except Exception as e:
    print("Not using auth, may be subject to rate limits")

try:
    with open("fastlane/weblate.txt", "r", encoding="utf-8") as f:
        WEBLATE_HEADERS["Authorization"] = "Bearer " + f.read().strip()
except Exception as e:
    print("Missing weblate API key")
    sys.exit(1)

def fetch_user_data(login: str) -> Optional[dict]:
    url = f"{API_BASE}{login}"
    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"❌ get users error {login}: {e}")
        return None

def fetch_translation_credits() -> Optional[dict]:
    try:
        # Step 1: Request report generation
        response = requests.post(
            WEBLATE_REPORTS,
            headers=WEBLATE_HEADERS,
            json={
                "kind": "credits",
                "project": "gramophone",
                "start": "1970-01-01T00:00:00Z",
                "end": "2099-01-01T00:00:00Z",
            },
            timeout=10,
        )
        response.raise_for_status()

        task_url = WEBLATE_BASE + response.json()["task_url"]

        # Step 2: Wait for task completion
        for _ in range(30):  # ~30 seconds max
            task = requests.get(
                task_url,
                headers=WEBLATE_HEADERS,
                timeout=10,
            )
            task.raise_for_status()

            task_data = task.json()

            if task_data.get("completed"):
                break

            time.sleep(1)
        else:
            print("❌ Timed out waiting for report generation")
            return None

        # Step 3: Find report URL
        report_url = WEBLATE_BASE + task_data["result"]["url"]

        # Step 4: Download report JSON
        report = requests.get(
            report_url + "json/",
            headers=WEBLATE_HEADERS,
            timeout=10,
        )
        report.raise_for_status()

        return report.json()

    except Exception as e:
        print(f"❌ get credits error: {e}")
        return None

def main():
    result = """// ===== DO NOT EDIT, CHANGES WILL BE OVERWRITTEN =====
// automatically generated by get_contributor_user_info.py

package org.akanework.gramophone.logic.utils.data

import android.net.Uri

object Contributors {
    private fun decode(text: String?) = text?.let { Uri.decode(it) }
    val LIST = listOf("""

    for user in GITHUB_USERS:
        login, lname = user if isinstance(user, tuple) else (user, user)
        print(f"📦 Processing users: {lname}")
        if login:
            user_data = fetch_user_data(login)
            if not user_data:
                return

            name = ("\"" + urllib.parse.quote(user_data["name"]) + "\"") if ("name" in user_data and user_data["name"]) else "null"
        else:
            name = f"\"{lname}\""
        result += f"\n        GitHubUser(login = \"{lname}\", name = decode({name})),"

    result += "\n    )\n"
    print("📦 Fetching credits from Weblate")
    credits = fetch_translation_credits()
    if not credits:
        return
    names = set()
    for language in credits:
        for users in language.values():
            for user in users:
                names.add(user["full_name"])
    result += "    val TRANSLATORS = listOf("
    names = sorted(names)
    for name in names:
        result += "\n        decode(\"" + urllib.parse.quote(name) + "\"),"
    result += "\n    )\n}\n"
    with open(OUTPUT_KT, "w", encoding="utf-8") as f:
        f.write(result)

    print(f"\n✅ All user processing is complete and results have been saved to {OUTPUT_KT}")

if __name__ == "__main__":
    main()
